apiVersion: apps/v1
kind: Deployment

metadata:
  name: restaurant-company
  labels:
    app: restaurant-company

spec:
  replicas: 2

  selector:
    matchLabels:
      app: restaurant-company

  template:
    metadata:
      labels:
        app: restaurant-company

    spec:
      containers:
        - name: restaurant-company

          image: 288673275952.dkr.ecr.us-east-2.amazonaws.com/restaurant-company:sha256:b0db947730844aaac2be13d8aec66ecc13220a93df57c224a98e36aeaf8ae9d9

          imagePullPolicy: Always

          ports:
            - containerPort: 80

          # Kubernetes checks if the application
          # is ready to receive traffic
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

          # Kubernetes checks if the application
          # is still alive
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
